---
title: Início
output:
  html_document:
    toc: true
    css:
      - CSS/logo-above-toc.css
      - CSS/narrow-margins.css
      - CSS/responsive.css
      - CSS/generic.css
      - CSS/main-color.css
---

<!--install and/or load all R packages-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%", results = "hide"}
# restart all variables
rm(list = ls(all = TRUE))

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '--',
  knitr.table.format = "html"
)
source("Scripts/all-required-packages.R", local = knitr::knit_global())
```

```{r main-color, results = "hide"}
# read CSS color for this page
css <- cssparser::read_css("CSS/main-color.css")
main.color <- css$`:root`$`--mybackgroundcolor`
```

<!--create (if non existent) all required folders-->
```{r folders, results = "hide"}
dir.create(file.path(getwd(), "PPG"), showWarnings = FALSE)
dir.create(file.path(getwd(), "Sucupira"), showWarnings = FALSE)
```

<!--read METRIC files-->
```{r metrics, results = "hide"}
source(file.path("Scripts", "citescore.R"), local = knitr::knit_global())
source(file.path("Scripts", "sjr.R"), local = knitr::knit_global())
source(file.path("Scripts", "webqualis.R"), local = knitr::knit_global())

source(file.path("Scripts", "get_citescore.R"),
       local = knitr::knit_global())
source(file.path("Scripts", "get_sjr.R"), local = knitr::knit_global())
source(file.path("Scripts", "get_webqualis.R"),
       local = knitr::knit_global())
# get metrics from Scopus, SCIMago and CAPES
source(file.path("Scripts", "get-metrics-from-sources.R"), local = knitr::knit_global())
```

```{r try-sucupira, results = "hide"}
files.to.read <-
  list.dirs(file.path(getwd(), "Sucupira"),
            full.names = TRUE,
            recursive = FALSE)
has.sucupira <- length(files.to.read) != 0
```

```{r try-ppg-files, results = "hide"}
# list all PPG files
files.to.read <-
  list.dirs(file.path(getwd(), "PPG"),
            full.names = TRUE,
            recursive = FALSE)
has.PPG.files <- length(files.to.read) != 0
```

<!--check available files in PPG folder-->
```{r try-agendas-pesquisa, results = "hide"}
has.agendas.pesquisa <-
  !is.error(try(readxl::read_excel("PPG/Agendas de Pesquisa.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-apresentacao, results = "hide"}
has.apresentacao <-
  !is.error(try(readxl::read_excel("PPG/Apresentação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-autoavaliacoes, results = "hide"}
has.autoavaliacoes <-
  !is.error(try(readxl::read_excel("PPG/Autoavaliações.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-avaliacao, results = "hide"}
has.avaliacao <-
  !is.error(try(readxl::read_excel("PPG/Avaliação.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-bibliografia, results = "hide"}
has.bibliografia <-
  !is.error(try(readxl::read_excel("PPG/Bibliografia.xlsx", sheet = 1),
                silent = TRUE))
```

```{r try-blog-externos, results = "hide"}
has.blog.externos <-
  !is.error(try(readxl::read_excel("PPG/Blog_externos.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-blog-ies, results = "hide"}
has.blog.ies <-
  !is.error(try(readxl::read_excel("PPG/Blog_IES.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-bolsas, results = "hide"}
has.bolsas <-
  !is.error(try(readxl::read_excel("PPG/Bolsas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-calendarios, results = "hide"}
has.calendarios <-
  !is.error(try(readxl::read_excel("PPG/Calendários.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-cep, results = "hide"}
has.cep <-
  !is.error(try(readxl::read_excel("PPG/CEP.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-colegiado, results = "hide"}
has.colegiado <-
  !is.error(try(readxl::read_excel("PPG/Colegiado.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-convenios, results = "hide"}
has.convenios <-
  !is.error(try(readxl::read_excel("PPG/Convênios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-cooperacoes, results = "hide"}
has.cooperacoes <-
  !is.error(try(readxl::read_excel("PPG/Cooperações.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-coordenacao, results = "hide"}
has.coordenacao <-
  !is.error(try(readxl::read_excel("PPG/Coordenação.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-dados-cadastrais, results = "hide"}
has.dados.cadastrais <-
  !is.error(try(readxl::read_excel("PPG/Dados Cadastrais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-destaques, results = "hide"}
has.destaques <-
  !is.error(try(readxl::read_excel("PPG/Destaques.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-discentes, results = "hide"}
has.discentes <-
  !is.error(try(readxl::read_excel("PPG/Discentes.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-downloads, results = "hide"}
has.downloads <-
  !is.error(try(readxl::read_excel("PPG/Downloads.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-editais, results = "hide"}
has.editais <-
  !is.error(try(readxl::read_excel("PPG/Editais.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-financiadores, results = "hide"}
has.financiadores <-
  !is.error(try(readxl::read_excel("PPG/Financiadores.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-grupos-pesquisa, results = "hide"}
has.grupos.pesquisa <-
  !is.error(try(readxl::read_excel("PPG/Grupos de Pesquisa.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-historico, results = "hide"}
has.historico <-
  !is.error(try(readxl::read_excel("PPG/Histórico.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-infraestrutura, results = "hide"}
has.infraestrutura <-
  !is.error(try(readxl::read_excel("PPG/Infraestrutura.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-internacionalizacao, results = "hide"}
has.internacionalizacao <-
  !is.error(try(readxl::read_excel("PPG/Internacionalização.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-laboratorios, results = "hide"}
has.laboratorios <-
  !is.error(try(readxl::read_excel("PPG/Laboratórios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-notas, results = "hide"}
has.notas <-
  !is.error(try(readxl::read_excel("PPG/Notas.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-premios, results = "hide"}
has.premios <-
  !is.error(try(readxl::read_excel("PPG/Prêmios.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r try-premio-capes, results = "hide"}
has.premio.capes <-
  !is.error(try(readxl::read_excel("PPG/Prêmio CAPES de Tese.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r producao-sucupira, results = "hide", eval = has.sucupira}
# produções
sheet <- "Produções - Detalhes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())

# Data selection
produtos <- sucupira.raw %>% dplyr::select(c("Subtipo de Produção", "Item de Detalhamento", "Valor do Item de Detalhamento"))

# Data cleaning
tipo <- "ARTIGO EM PERIÓDICO"
natureza <- "Completo"
titles <-
  produtos$"Nome da Produção"[produtos$"Item de Detalhamento" == natureza]
produtos.completos <- produtos[produtos$"Nome da Produção" == titles,]
doi_artigos_completos_sucupira <- 
  data.frame(produtos.completos$"Valor do Item de Detalhamento"[
    (produtos.completos$"Subtipo de Produção" == tipo)
    &
    (produtos.completos$"Item de Detalhamento" == "Número do DOI")
    ])
doi_artigos_completos_sucupira <- na.omit(doi_artigos_completos_sucupira)
colnames(doi_artigos_completos_sucupira) <- "DOI"

# Data cleaning
tipo <- "ARTIGO EM PERIÓDICO"
natureza <- "Resumo"
titles <-
  produtos$"Nome da Produção"[produtos$"Item de Detalhamento" == natureza]
produtos.resumos <- produtos[produtos$"Nome da Produção" == titles,]

# Data cleaning
doi_artigos_resumos_sucupira <- 
  data.frame(produtos.resumos$"Valor do Item de Detalhamento"[
    (produtos.resumos$"Subtipo de Produção" == tipo)
    &
    (produtos.resumos$"Item de Detalhamento" == "Número do DOI")
    ])
doi_artigos_resumos_sucupira <- na.omit(doi_artigos_resumos_sucupira)
colnames(doi_artigos_resumos_sucupira) <- "DOI"
```

```{r try-producao-ppg, results = "hide"}
has.artigos.completos <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.completos"),
                silent = TRUE))
if(!has.artigos.completos){
  doi_unique_artigos = data.frame()
  my_doi_works_artigos = data.frame()
  references_artigos = data.frame()
  doi_unique_artigos_impacto = data.frame()
  my_doi_works_artigos_impacto = data.frame()
  }

has.artigos.resumos <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.resumos"), silent = TRUE))
if(!has.artigos.resumos){
  doi_unique_resumos = data.frame()
  my_doi_works_resumos = data.frame()
  references_resumos = data.frame()
  doi_unique_resumos_impacto = data.frame()
  my_doi_works_resumos_impacto = data.frame()
  }

has.preprints <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.preprints"),
                silent = TRUE))
if(!has.preprints){
  doi_unique_preprints = data.frame()
  my_doi_works_preprints = data.frame()
  references_preprints = data.frame()
  doi_unique_preprints_impacto = data.frame()
  my_doi_works_preprints_impacto = data.frame()
  }

has.livros <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.livros"), silent = TRUE))
if(!has.livros){
  doi_unique_livros = data.frame()
  my_doi_works_livros = data.frame()
  references_livros = data.frame()
  doi_unique_livros_impacto = data.frame()
  my_doi_works_livros_impacto = data.frame()
  }

has.capitulos <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.capitulos"), silent = TRUE))
if(!has.capitulos){
  doi_unique_capitulos = data.frame()
  my_doi_works_capitulos = data.frame()
  references_capitulos = data.frame()
  doi_unique_capitulos_impacto = data.frame()
  my_doi_works_capitulos_impacto = data.frame()
  }

has.eventos <-
  !is.error(try(readxl::read_excel("PPG/Produção.xlsx", sheet = "PI.eventos"), silent = TRUE))
if(!has.eventos){
  doi_unique_eventos = data.frame()
  my_doi_works_eventos = data.frame()
  references_eventos = data.frame()
  doi_unique_eventos_impacto = data.frame()
  my_doi_works_eventos_impacto = data.frame()
  }

has.producao <-
  any(has.artigos.completos,
      has.artigos.resumos,
      has.preprints,
      has.livros,
      has.capitulos,
      has.eventos)
```

```{r try-repositorios, results = "hide"}
has.repositorios.sede <-
  !is.error(try(readxl::read_excel("PPG/Repositórios.xlsx", sheet =  "Sede"),
                silent = TRUE)
  )

has.repositorios.cooperacao <-
  !is.error(try(readxl::read_excel("PPG/Repositórios.xlsx", sheet = "Cooperação"),
                silent = TRUE)
  )
```

```{r try-softwares, results = "hide"}
has.softwares <-
  !is.error(try(readxl::read_excel("PPG/Softwares.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r ppg-data, results = "hide", eval = and(has.dados.cadastrais, has.sucupira)}
# get initials from the PPG data
nome.PPG <-
  readxl::read_excel("PPG/Dados Cadastrais.xlsx",
             sheet = "Dados do programa",
             col_types = c("text"))[2, 2]

nome.PPG.split <- stringr::str_split_1(as.character(nome.PPG)[[1]], " ")
match.stopwords <-
  match(stringr::str_split_1(as.character(nome.PPG)[[1]], " "), tm::stopwords("portuguese"))
nome.PPG.no.stopwords <-
  paste(nome.PPG.split[is.na(match.stopwords)], collapse = " ")
source("Scripts/get-initials.R")
sigla.PPG <- initials(nome.PPG.no.stopwords)

site.PPG <-
  readxl::read_excel("PPG/Dados Cadastrais.xlsx",
             sheet = "Endereço",
             col_types = c("text"))[7, 2]

# qualquer planilha para obter os dados da IES
sheet <- "Docentes"
source("Scripts/read-xlsx-sucupira.R", local = knitr::knit_global())
nome.IES <- unique(sucupira.raw$`IES Nome`)
sigla.IES <- unique(sucupira.raw$`IES Sigla`)
```

<!--get data-->
```{r metrics-artigos, results = "hide", cache = TRUE, cache.path = "cache/artigos/", eval = has.artigos.completos}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.completos",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", colnames(data.sheet))])

# bind PPG and SUCUPIRA DOIs
if (!is.null(get0("doi_artigos_completos_sucupira"))) {
  dois <- data.frame(DOI = c(doi_artigos_completos_sucupira$DOI, dois$DOI))
}

# Data cleaning
dois <-data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = do::unique_no.NA(dois$DOI))

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())

# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_artigos <- dois
doi_unique_artigos <- get_metrics(df = doi_unique, citescore, scimago, qualis)
my_doi_works_artigos <- get_metrics(df = my_doi_works, citescore, scimago, qualis)

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_doi_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_artigos <- formatted_citations
```

<!--get data-->
```{r metrics-resumos, results = "hide", cache = TRUE, cache.path = "cache/resumos/", eval = has.artigos.resumos}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.resumos",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", colnames(data.sheet))])

# bind PPG and SUCUPIRA DOIs
if (!is.null(get0("doi_artigos_resumos_sucupira"))) {
  dois <- data.frame(DOI = c(doi_artigos_resumos_sucupira$DOI, dois$DOI))
}

# Data cleaning
dois <-data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = do::unique_no.NA(dois$DOI))

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())

# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_resumos <- dois
doi_unique_resumos <- get_metrics(df = doi_unique, citescore, scimago, qualis)
my_doi_works_resumos <- get_metrics(df = my_doi_works, citescore, scimago, qualis)

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_doi_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_resumos <- formatted_citations
```

<!--get data-->
```{r metrics-preprints, results = "hide", cache = TRUE, cache.path = "cache/preprints/", eval = has.preprints}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.preprints",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", colnames(data.sheet))])

# Data cleaning
dois <-data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = do::unique_no.NA(dois$DOI))

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())

# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_preprints <- dois
doi_unique_preprints <- get_metrics(df = doi_unique, citescore, scimago, qualis)
my_doi_works_preprints <- get_metrics(df = my_doi_works, citescore, scimago, qualis)

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_doi_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_preprints <- formatted_citations
```

<!--get data-->
```{r metrics-livros, results = "hide", cache = TRUE, cache.path = "cache/livros/", eval = has.livros}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.livros",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", colnames(data.sheet))])

# Data cleaning
dois <-data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = do::unique_no.NA(dois$DOI))

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())

# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_livros <- dois
doi_unique_livros <- get_metrics(df = doi_unique, citescore, scimago, qualis)
my_doi_works_livros <- get_metrics(df = my_doi_works, citescore, scimago, qualis)

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_doi_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_livros <- formatted_citations
```

<!--get data-->
```{r metrics-capitulos, results = "hide", cache = TRUE, cache.path = "cache/capitulos/", eval = has.capitulos}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.capitulos",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", colnames(data.sheet))])

# Data cleaning
dois <-data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = do::unique_no.NA(dois$DOI))

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())

# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_capitulos <- dois
doi_unique_capitulos <- get_metrics(df = doi_unique, citescore, scimago, qualis)
my_doi_works_capitulos <- get_metrics(df = my_doi_works, citescore, scimago, qualis)

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_doi_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_capitulos <- formatted_citations
```

<!--get data-->
```{r metrics-eventos, results = "hide", cache = TRUE, cache.path = "cache/eventos/", eval = has.eventos}
# read data
data.sheet <-
  data.frame(readxl::read_excel(
    "PPG/Produção.xlsx",
    sheet = "PI.eventos",
    col_types = c("text")
  ))

# select DOI column
dois <-
  data.frame(DOI = data.sheet[, match("DOI", colnames(data.sheet))])

# Data cleaning
dois <-data.frame(DOI = dois$DOI[!duplicated(dois)])
dois <- data.frame(DOI = do::unique_no.NA(dois$DOI))

# cria metadados para rastreio pelo Altmetric
source("Scripts/altmetric-meta-from-dois.R", local = knitr::knit_global())

# get metrics from Altmetric and CrossRef
source("Scripts/get-metrics-from-dois.R", local = knitr::knit_global())

# store to use downstream
dois_eventos <- dois
doi_unique_eventos <- get_metrics(df = doi_unique, citescore, scimago, qualis)
my_doi_works_eventos <- get_metrics(df = my_doi_works, citescore, scimago, qualis)

# obtain formatted references
formatted_citations <-
  rcrossref::cr_cn(
    c(doi_unique$doi, my_doi_works$doi),
    format = "text",
    raw = TRUE,
    style = "american-medical-association"
  )
formatted_citations <- substring(formatted_citations, 3)
formatted_citations <-
  cbind(seq(1, length(formatted_citations)), formatted_citations)
colnames(formatted_citations) <- c("ID", "Reference")

references_eventos <- formatted_citations
```

```{r bind-all, results = "hide", cache = TRUE, cache.path = "cache/bind-all/", eval = has.producao}
# bind sources
doi_unique_all <-
  dplyr::bind_rows(
    doi_unique_artigos,
    doi_unique_resumos,
    doi_unique_preprints,
    doi_unique_livros,
    doi_unique_capitulos,
    doi_unique_eventos
  ) %>%
  as.data.frame()

# bind sources
my_doi_works_all <-
  dplyr::bind_rows(
    my_doi_works_artigos,
    my_doi_works_resumos,
    my_doi_works_preprints,
    my_doi_works_livros,
    my_doi_works_capitulos,
    my_doi_works_eventos
  ) %>%
  as.data.frame()

# bind common data
doi_all <-
  dplyr::bind_rows(doi_unique_all,
                   my_doi_works_all) %>%
  as.data.frame()

references_all <-
  rbind(
    references_artigos,
    references_resumos,
    references_preprints,
    references_livros,
    references_capitulos,
    references_eventos
  ) %>%
  as.data.frame()
```

```{r retratacoes, results = "hide", cache = TRUE, cache.path = "cache/retratacoes/", eval = has.producao}
# bind sources
dois_unique_retracted <- c()
for (i in 1:dim(doi_unique_all)[1]) {
  if (!retractcheck::check_doi(doi = as.character(doi_unique_all$doi[i]))) {
    dois_unique_retracted <-
      rbind(dois_unique_retracted, doi_unique_all[i,])
  }
}

my_doi_works_retracted <- c()
# my_doi_works_retracted <- c()
for (i in 1:dim(my_doi_works_all)[1]) {
  if (!retractcheck::check_doi(doi = as.character(my_doi_works_all$doi[i]))) {
    my_doi_works_retracted <-
      rbind(my_doi_works_retracted, my_doi_works_all[i,])
  }
}
```

```{r has, results = "hide", cache = TRUE, cache.path = "cache/has/", eval = has.producao}
has.agendas.pesquisa
has.apresentacao
has.artigos.completos
has.artigos.resumos
has.autoavaliacoes
has.avaliacao
has.bibliografia
has.blog.externos
has.blog.ies
has.bolsas
has.calendarios
has.capitulos
has.cep
has.colegiado
has.convenios
has.cooperacoes
has.coordenacao
has.dados.cadastrais
has.destaques
has.discentes
has.downloads
has.editais
has.eventos
has.financiadores
has.grupos.pesquisa
has.historico
has.infraestrutura
has.internacionalizacao
has.laboratorios
has.livros
has.notas
has.PPG.files
has.premio.capes
has.premios
has.preprints
has.producao
has.repositorios.cooperacao
has.repositorios.sede
has.softwares
has.sucupira
```
