---
title: Caches
output:
  html_document:
    toc: true
    toc_float: true
    css:
      - ./CSS/generic.css
      - ./CSS/logo-above-toc.css
      - ./CSS/main-color.css
      - ./CSS/narrow-margins.css
      - ./CSS/responsive.css
---

<!--install and/or load all R packages-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%"}
# restart all variables
rm(list = ls(all = TRUE))

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '',
  knitr.table.format = ifelse(knitr::is_html_output(), "html", "latex"),
  webshot = "webshot",
  dev = "png"
)
```

```{r load-caches, echo = FALSE, include = FALSE}
folders <- list.dirs(file.path("cache/"), full.names = FALSE, recursive = FALSE)
for(folder in folders){
    knitr::load_cache(label = folder, path = paste0(file.path("cache", folder), "/"))
}
```
